# Generated by Django 2.2.24 on 2021-06-14 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('capacidade', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('dataDeNascimento', models.DateField()),
                ('endereco', models.CharField(max_length=60)),
                ('telefone', models.IntegerField()),
                ('rg', models.IntegerField()),
                ('dataRG', models.DateField()),
                ('email', models.CharField(max_length=60)),
                ('numeroCartao', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=90)),
                ('telefone', models.IntegerField()),
                ('categoria', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ListaDeServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelariaIFBA.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('formaDePagamento', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('alojamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelariaIFBA.Alojamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelariaIFBA.Cliente')),
                ('listaDeServico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelariaIFBA.ListaDeServico')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=60)),
                ('preco', models.IntegerField()),
                ('numPessoas', models.IntegerField()),
                ('periodo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ServicosUtilizados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelariaIFBA.Reserva')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelariaIFBA.ListaDeServico')),
            ],
        ),
        migrations.AddField(
            model_name='listadeservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelariaIFBA.TipoServico'),
        ),
        migrations.CreateModel(
            name='Empregados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('funcao', models.CharField(max_length=30)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelariaIFBA.Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='alojamento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelariaIFBA.Empresa'),
        ),
    ]
