# Generated by Django 2.2.24 on 2021-06-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelariaIFBA', '0003_auto_20210621_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='categoria',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Pousada', 'Pousada'), ('Sitio', 'Sitio'), ('Hostel', 'Hostel')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('Reservado', 'Reservado'), ('Finalizado', 'Finalizado'), ('Em andamento', 'Em andamento'), ('Cancelado', 'Cancelado')], max_length=30),
        ),
    ]
