# Generated by Django 2.2.24 on 2021-06-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelariaIFBA', '0005_auto_20210628_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervico',
            name='periodo',
            field=models.CharField(choices=[('Temporada', 'Temporada'), ('Não Temporada', 'Não Temporada')], max_length=30),
        ),
    ]
