# Generated by Django 2.2.24 on 2021-06-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelariaIFBA', '0006_auto_20210628_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='formaDePagamento',
            field=models.CharField(choices=[('Cartao_Debito', 'Cartao_Debito'), ('Cartao_Credito', 'Cartao_Credito'), ('A Vista', 'A Vista'), ('Cheque', 'Cheque')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='periodo',
            field=models.CharField(choices=[('Temporada', 'Temporada'), ('Fora Temporada', 'Fora Temporada')], max_length=30),
        ),
    ]
