# Generated by Django 2.2.24 on 2021-06-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelariaIFBA', '0011_auto_20210629_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamento',
            name='diaria',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
