# Generated by Django 2.2.24 on 2021-06-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelariaIFBA', '0012_auto_20210629_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamento',
            name='descricao',
            field=models.CharField(default='nomedefault', max_length=30),
            preserve_default=False,
        ),
    ]
