# Generated by Django 2.2.24 on 2021-06-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelariaIFBA', '0013_alojamento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamento',
            name='diaria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='preco',
            field=models.FloatField(),
        ),
    ]
