# Generated by Django 2.2.24 on 2021-07-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelariaIFBA', '0014_auto_20210630_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposervico',
            old_name='nome',
            new_name='servico',
        ),
    ]
